// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByaNJZjhXfedXhs-71GjazPYhegb36bBM',
    appId: '1:910935241512:web:15533661247267339d561d',
    messagingSenderId: '910935241512',
    projectId: 'ojt-monitoring-system-44070',
    authDomain: 'ojt-monitoring-system-44070.firebaseapp.com',
    storageBucket: 'ojt-monitoring-system-44070.firebasestorage.app',
    measurementId: 'G-QK59E8TEW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy5YN8oaiA7tf418swVGq5Mtj6Yd1INiU',
    appId: '1:910935241512:android:59c60bf39c999ec89d561d',
    messagingSenderId: '910935241512',
    projectId: 'ojt-monitoring-system-44070',
    storageBucket: 'ojt-monitoring-system-44070.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyqxLf8qLqvv616Hmjj-cyhfjnKiq5luA',
    appId: '1:910935241512:ios:271ca219b2ca3f3d9d561d',
    messagingSenderId: '910935241512',
    projectId: 'ojt-monitoring-system-44070',
    storageBucket: 'ojt-monitoring-system-44070.firebasestorage.app',
    androidClientId: '910935241512-6g1oas5rl47se3aibrgdo3q7tnb7qci5.apps.googleusercontent.com',
    iosClientId: '910935241512-cefao69qh8621g7o3ird2bvtr12qqad2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ojtMonitoringApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyqxLf8qLqvv616Hmjj-cyhfjnKiq5luA',
    appId: '1:910935241512:ios:271ca219b2ca3f3d9d561d',
    messagingSenderId: '910935241512',
    projectId: 'ojt-monitoring-system-44070',
    storageBucket: 'ojt-monitoring-system-44070.firebasestorage.app',
    androidClientId: '910935241512-6g1oas5rl47se3aibrgdo3q7tnb7qci5.apps.googleusercontent.com',
    iosClientId: '910935241512-cefao69qh8621g7o3ird2bvtr12qqad2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ojtMonitoringApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByaNJZjhXfedXhs-71GjazPYhegb36bBM',
    appId: '1:910935241512:web:e010dbf33a9859519d561d',
    messagingSenderId: '910935241512',
    projectId: 'ojt-monitoring-system-44070',
    authDomain: 'ojt-monitoring-system-44070.firebaseapp.com',
    storageBucket: 'ojt-monitoring-system-44070.firebasestorage.app',
    measurementId: 'G-6V90JJ9QTN',
  );
}
